### ISSUE TITLE
Confused about completion

### ISSUE THREAD

**Issue by trev-dev** [PaterJason/cmp-conjure#3]
Sorry, this isn't necessarily an issue with cmp-conjure!  I'm just not sure my setup is working correctly.  I do see completions from other sources in my config...but whenever I'm in a lispy buffer, usually repl'd by Guile or Fennel, but the completions I get are of the "Text" kind. 

I can't tell if this is coming from the REPL or not.  I think likely not as they don't seem contextually brilliant.

I am set up as such: https://git.sr.ht/~trevdev/nvim/tree/main/item/fnl/tdev/package/cmp.fnl

**Comment by PaterJason** [comment]
Looking at the conjure code, completion is only supported for Clojure (nrepl) and Fennel (Aniseed). There's a dictionary of types for both of those. I've tested fennel completions and have type signatures. Are you sure the completions are coming from cmp-conjure and not another source (e.g. cmp-buffer)?

**Comment by trev-dev** [comment]
I see!  The Conjure readme has instructions about how to connect to a REPL in various other lisp formats.  One such example is [Guile over a socket](https://github.com/Olical/conjure/wiki/Quick-start:-Guile-(socket)).  The evals technically work though they are not always that helpful and completions don't happen either.  Maybe its safe to say the say that these other repls aren't totally supported.

**Comment by trev-dev** [comment]
Theeere it is: https://github.com/Olical/conjure/wiki/Client-features

Thanks for having a look!
